### ISSUE TITLE
Permissions of created files

### ISSUE THREAD

**Issue by dbrgn** [seanmonstar/futures-fs#18]
Is there a way to specify the permissions of newly created files when using `fs.write`?

I'm writing files where I want to ensure that they are never world or group accessible.

(I could also create the empty file first and then write to it, but maybe there's a nice way how that could be put into the `futures-fs` API?)

**Comment by seanmonstar** [comment]
You can specify the `OpenOptions` and convert it into the `WriteOptions` used.

**Comment by dbrgn** [comment]
Oh, I missed the OpenOptions impl for the `OpenOptionsExt` trait :) Thanks!
