### ISSUE TITLE
Construct streams from files

### ISSUE THREAD

**Issue by millardjn** [seanmonstar/futures-fs#8]
Hi,

I'm looking to perform async reads/writes to an existing `File` rather than a path. Is it possible to add a way convert a `File` into a `FsReadStream` and `FsWriteSink`?

I had a quick look at the code and was wondering if a `from_file(...)` constructor function could be added where state is initialised as a `State::Ready(...)` and the `Pathbuf` was left blank.

Happy to put a PR together if you think this can work.

**Comment by seanmonstar** [comment]
Yea, that seems fine!

**Comment by shepmaster** [comment]
Seems to have been closed by #9 ?
